### ISSUE TITLE
Failed linter on GitHub Actions run does not cause check to fail when fail_on_error is true

### ISSUE THREAD

**Issue by Doarakko** [reviewdog/reviewdog#949]
Many repositories need to fix, so please help if you like.

If you could help, it would be helpful if you could comment before starting the work not to overlapping.

![](https://user-images.githubusercontent.com/21009186/118365981-cefab680-b5d9-11eb-8395-6fa4c4dcfb52.png)

## Fix example

Run exit command after lint.

```sh
echo '::group:: Running golangci-lint with reviewdog 🐶 ...'
golangci-lint run --out-format line-number ${INPUT_GOLANGCI_LINT_FLAGS} \
  | reviewdog -f=golangci-lint \
      -name="${INPUT_TOOL_NAME}" \
      -reporter="${INPUT_REPORTER:-github-pr-check}" \
      -filter-mode="${INPUT_FILTER_MODE:-added}" \
      -fail-on-error="${INPUT_FAIL_ON_ERROR:-false}" \
      -level="${INPUT_LEVEL}" \
      ${INPUT_REVIEWDOG_FLAGS}
exit_code=$?
echo '::endgroup::'

exit $exit_code
```

https://github.com/reviewdog/action-golangci-lint/pull/77

## Todo

I checked the ones that are runnning exit command.

If `fail_on_error` is not exist in input, please add.

- Template
  - [ ] [reviewdog/action-template](https://github.com/reviewdog/action-template)
- Common
  - [ ] [reviewdog/action-misspell](https://github.com/reviewdog/action-misspell) - Run [misspell](https://github.com/client9/misspell).
- Text (e.g. Markdown)
  - [ ] [reviewdog/action-alex](https://github.com/reviewdog/action-alex) - Run [alex](https://github.com/get-alex/alex) which catches insensitive, inconsiderate writing. (e.g. master/slave)
  - [ ] [reviewdog/action-languagetool](https://github.com/reviewdog/action-languagetool) - Run [languagetool](https://github.com/languagetool-org/languagetool).
  - [ ] [tsuyoshicho/action-textlint](https://github.com/tsuyoshicho/action-textlint) - Run [textlint](https://github.com/textlint/textlint)
  - [ ] [tsuyoshicho/action-redpen](https://github.com/tsuyoshicho/action-redpen) - Run [redpen](https://github.com/redpen-cc/redpen)
- Docker
  - [x] [reviewdog/action-hadolint](https://github.com/reviewdog/action-hadolint) - Run [hadolint](https://github.com/hadolint/hadolint) to lint `Dockerfile`.
- Env
  - [x] [dotenv-linter/action-dotenv-linter](https://github.com/dotenv-linter/action-dotenv-linter) - Run [dotenv-linter](https://github.com/dotenv-linter/dotenv-linter) to lint `.env` files.
- Shell script
  - [ ] [reviewdog/action-shellcheck](https://github.com/reviewdog/action-shellcheck) - Run [shellcheck](https://github.com/koalaman/shellcheck).
- Go
  - [ ] [reviewdog/action-staticcheck](https://github.com/reviewdog/action-staticcheck) - Run [staticcheck](https://staticcheck.io/).
  - [x] [reviewdog/action-golangci-lint](https://github.com/reviewdog/action-golangci-lint) - Run [golangci-lint](https://github.com/golangci/golangci-lint) and supported linters individually by golangci-lint.
- JavaScript
  - [x] [reviewdog/action-eslint](https://github.com/reviewdog/action-eslint) - Run [eslint](https://github.com/eslint/eslint).
- CSS
  - [ ] [reviewdog/action-stylelint](https://github.com/reviewdog/action-stylelint) - Run [stylelint](https://github.com/stylelint/stylelint).
- Vim script
  - [ ] [reviewdog/action-vint](https://github.com/reviewdog/action-vint) - Run [vint](https://github.com/Kuniwak/vint).
  - [ ] [tsuyoshicho/action-vimlint](https://github.com/tsuyoshicho/action-vimlint) - Run [vim-vimlint](https://github.com/syngan/vim-vimlint)
- Terraform
  - [x] [reviewdog/action-tflint](https://github.com/reviewdog/action-tflint) - Run [tflint](https://github.com/wata727/tflint).
- YAML
  - [ ] [reviewdog/action-yamllint](https://github.com/reviewdog/action-yamllint) - Run [yamllint](https://github.com/adrienverge/yamllint).
- Ruby
  - [ ] [reviewdog/action-brakeman](https://github.com/reviewdog/action-brakeman) - Run [brakeman](https://github.com/presidentbeef/brakeman).
  - [x] [reviewdog/action-reek](https://github.com/reviewdog/action-reek) - Run [reek](https://github.com/troessner/reek).
  - [x] [reviewdog/action-rubocop](https://github.com/reviewdog/action-rubocop) - Run [rubocop](https://github.com/rubocop-hq/rubocop).
  - [ ] [vk26/action-fasterer](https://github.com/vk26/action-fasterer) - Run [fasterer](https://github.com/DamirSvrtan/fasterer).
  - [ ] [SennaLabs/action-standardrb](https://github.com/SennaLabs/action-standardrb) - Run [standardrb](https://github.com/testdouble/standard).

- Python
  - [x] [wemake-python-styleguide](https://github.com/wemake-services/wemake-python-styleguide) - Run wemake-python-styleguide
  - [x] [tsuyoshicho/action-mypy](https://github.com/tsuyoshicho/action-mypy) - Run [mypy](https://pypi.org/project/mypy/)
- Kotlin
  - [ ] [ScaCap/action-ktlint](https://github.com/ScaCap/action-ktlint) - Run [ktlint](https://ktlint.github.io/).
- Android Lint
  - [ ] [dvdandroid/action-android-lint](https://github.com/DVDAndroid/action-android-lint) - Run [Android Lint](https://developer.android.com/studio/write/lint)
- Ansible
  - [x] [reviewdog/action-ansiblelint](https://github.com/reviewdog/action-ansiblelint) - Run [ansible-lint](https://github.com/ansible/ansible-lint)

ref: https://github.com/reviewdog/reviewdog#public-reviewdog-github-actions

**Comment by Doarakko** [comment]
Some repositories seem to fail the check successfully without running exit command.

example

- yamllint
    - https://github.com/Doarakko/reviewdog-playground/pull/16
- staticcheck
    - https://github.com/Doarakko/reviewdog-playground/pull/13

I haven't checked all the repositories yet.

I think it is better to run exit command in a unified manner than to think whether it is necessary to run exit command because it can prevent problems like this one.

At least I'm thinking of adding it to the template repository.
https://github.com/reviewdog/action-template

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.001 ETH (2.25 USD @ $2245.09/ETH)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/reviewdog/reviewdog/949/100025986).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/reviewdog/reviewdog/949/100025986).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $2,135,501.20 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 265 years, 5 months from now.
Please review their action plans below:


**1) [richcrown619](https://gitcoin.co/richcrown619) has started work.**

I will to support this project at all cost

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/reviewdog/reviewdog/949/100025986).

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work for 0.001 ETH  has been submitted by__:

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/reviewdog/reviewdog/949/100025986)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/reviewdog/reviewdog/949/100025986).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $2,123,922.71 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by hisuwh** [comment]
What's the state of this one.  I have got es-lint errors and am exceeding --max-warnings and reviewdog/action-eslint is not failing my build.

**Comment by Djiit** [comment]
Hi there 👋  stylelint seems to have it, but yet the action is not failing when stylelint fails. Any idea? https://github.com/reviewdog/action-stylelint/blob/master/script.sh#L40

**Comment by Doarakko** [comment]
@Djiit 
It worked fine here.
https://github.com/Doarakko/reviewdog-playground/pull/17

Can you share a repository that isn't working properly?

**Comment by vincent067** [comment]
Hi @Doarakko and team! 👋

I'd like to help with fixing the exit code issue across the reviewdog actions. I've just submitted a PR for **action-alex**:

🔗 https://github.com/reviewdog/action-alex/pull/59

This follows the same pattern from action-golangci-lint#77 - removing , capturing the exit code, and propagating it at the end.

If this looks good, I'd be happy to help with some of the other unchecked actions on the list (like action-shellcheck, action-yamllint, or action-staticcheck). Just let me know which ones would be most helpful to tackle next!

Thanks for maintaining such a great ecosystem 🙏
